model_name: 'Yolov7Obj'
model_dir_name: 'yolov7_obj'

train_txt: ''
val_txt: ''
data_file: "./model_zoo/yolov7_obj/data/coco.yaml"
hyp_file: "./model_zoo/yolov7_obj/data/hyp.scratch.p6.yaml"
cfg_file: "./model_zoo/yolov7_obj/cfg/training/yolov7-e6e.yaml"



