# ===========Augmentation===========
hsv_h: 0.  # image HSV-Hue augmentation (fraction)
hsv_s: 0.  # image HSV-Saturation augmentation (fraction)
hsv_v: 0.  # image HSV-Value augmentation (fraction)
degrees: 0.0  # image rotation (+/- deg)
translate: 0.  # image translation (+/- fraction)
scale: 1.  # image scale (+/- gain)
shear: 0.0  # image shear (+/- deg)
perspective: 0.0  # image perspective (+/- fraction), range 0-0.001
flipud: 0.0  # image flip up-down (probability)
fliplr: 0.  # image flip left-right (probability)
mosaic: 0.  # image mosaic (probability)
mixup: 0.  # image mixup (probability)
copy_paste: 0.  # segment copy-paste (probability)