# ===========Hyperparameter===========
optimizer: "Adam" # Adam、AdamW、SGD
weight: ""
start_epoch: 0
end_epoch: 300
lr: 0.01
start_factor: 0.3
batch_size: 16
imgsz: [640, 640] # H, W
device: '0' # cuda device, i.e. 0 or 0,1,2,3 or cpu