# ===========Data file===========
data_file:
  # Dataset
  download: bash ./scripts/get_coco.sh
  train: ./coco/train2017.txt
  val: ./coco/val2017.txt
  test: ./coco/test-dev2017.txt

  # number of classes
  nc: 80

  # class names
  names: [ 'person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus', 'train', 'truck', 'boat', 'traffic light',
           'fire hydrant', 'stop sign', 'parking meter', 'bench', 'bird', 'cat', 'dog', 'horse', 'sheep', 'cow',
           'elephant', 'bear', 'zebra', 'giraffe', 'backpack', 'umbrella', 'handbag', 'tie', 'suitcase', 'frisbee',
           'skis', 'snowboard', 'sports ball', 'kite', 'baseball bat', 'baseball glove', 'skateboard', 'surfboard',
           'tennis racket', 'bottle', 'wine glass', 'cup', 'fork', 'knife', 'spoon', 'bowl', 'banana', 'apple',
           'sandwich', 'orange', 'broccoli', 'carrot', 'hot dog', 'pizza', 'donut', 'cake', 'chair', 'couch',
           'potted plant', 'bed', 'dining table', 'toilet', 'tv', 'laptop', 'mouse', 'remote', 'keyboard', 'cell phone',
           'microwave', 'oven', 'toaster', 'sink', 'refrigerator', 'book', 'clock', 'vase', 'scissors', 'teddy bear',
           'hair drier', 'toothbrush' ]

# ===========Hyperparameter file===========
hyp_file:
  lr0: 0.01  # initial learning rate (SGD=1E-2, Adam=1E-3)
  lrf: 0.1  # final OneCycleLR learning rate (lr0 * lrf)
  momentum: 0.937  # SGD momentum/Adam beta1
  weight_decay: 0.0005  # optimizer weight decay 5e-4
  warmup_epochs: 3.0  # warmup epochs (fractions ok)
  warmup_momentum: 0.8  # warmup initial momentum
  warmup_bias_lr: 0.1  # warmup initial bias lr
  box: 0.05  # box loss gain
  cls: 0.3  # cls loss gain
  cls_pw: 1.0  # cls BCELoss positive_weight
  obj: 0.7  # obj loss gain (scale with pixels)
  obj_pw: 1.0  # obj BCELoss positive_weight
  iou_t: 0.20  # IoU training threshold
  anchor_t: 4.0  # anchor-multiple threshold
  fl_gamma: 0.0  # focal loss gamma (efficientDet default gamma=1.5)
  hsv_h: 0.015  # image HSV-Hue augmentation (fraction)
  hsv_s: 0.7  # image HSV-Saturation augmentation (fraction)
  hsv_v: 0.4  # image HSV-Value augmentation (fraction)
  degrees: 0.0  # image rotation (+/- deg)
  translate: 0.1  # image translation (+/- fraction)
  scale: 0.9  # image scale (+/- gain)
  shear: 0.0  # image shear (+/- deg)
  perspective: 0.0  # image perspective (+/- fraction), range 0-0.001
  flipud: 0.0  # image flip up-down (probability)
  fliplr: 0.5  # image flip left-right (probability)
  mosaic: 1.0  # image mosaic (probability)
  mixup: 0.1  # image mixup (probability)
  copy_paste: 0.1  # segment copy-paste (probability)

# ===========Training setting===========
model:
  # Parameters
  nc: 80  # number of classes
  depth_multiple: 1.0  # model depth multiple
  width_multiple: 1.0  # layer channel multiple
  anchors:
    - [ 12,16, 19,36, 40,28 ]  # P3/8
    - [ 36,75, 76,55, 72,146 ]  # P4/16
    - [ 142,110, 192,243, 459,401 ]  # P5/32

  # YOLOv7 backbone
  backbone:
    # [from, number, module, args]
    [ [ -1, 1, Conv, [ 32, 3, 1 ] ],  # 0

      [ -1, 1, Conv, [ 64, 3, 2 ] ],  # 1-P1/2
      [ -1, 1, Conv, [ 64, 3, 1 ] ],

      [ -1, 1, Conv, [ 128, 3, 2 ] ],  # 3-P2/4
      [ -1, 1, Conv, [ 64, 1, 1 ] ],
      [ -2, 1, Conv, [ 64, 1, 1 ] ],
      [ -1, 1, Conv, [ 64, 3, 1 ] ],
      [ -1, 1, Conv, [ 64, 3, 1 ] ],
      [ -1, 1, Conv, [ 64, 3, 1 ] ],
      [ -1, 1, Conv, [ 64, 3, 1 ] ],
      [ [ -1, -3, -5, -6 ], 1, Concat, [ 1 ] ],
      [ -1, 1, Conv, [ 256, 1, 1 ] ],  # 11

      [ -1, 1, MP, [ ] ],
      [ -1, 1, Conv, [ 128, 1, 1 ] ],
      [ -3, 1, Conv, [ 128, 1, 1 ] ],
      [ -1, 1, Conv, [ 128, 3, 2 ] ],
      [ [ -1, -3 ], 1, Concat, [ 1 ] ],  # 16-P3/8
      [ -1, 1, Conv, [ 128, 1, 1 ] ],
      [ -2, 1, Conv, [ 128, 1, 1 ] ],
      [ -1, 1, Conv, [ 128, 3, 1 ] ],
      [ -1, 1, Conv, [ 128, 3, 1 ] ],
      [ -1, 1, Conv, [ 128, 3, 1 ] ],
      [ -1, 1, Conv, [ 128, 3, 1 ] ],
      [ [ -1, -3, -5, -6 ], 1, Concat, [ 1 ] ],
      [ -1, 1, Conv, [ 512, 1, 1 ] ],  # 24

      [ -1, 1, MP, [ ] ],
      [ -1, 1, Conv, [ 256, 1, 1 ] ],
      [ -3, 1, Conv, [ 256, 1, 1 ] ],
      [ -1, 1, Conv, [ 256, 3, 2 ] ],
      [ [ -1, -3 ], 1, Concat, [ 1 ] ],  # 29-P4/16
      [ -1, 1, Conv, [ 256, 1, 1 ] ],
      [ -2, 1, Conv, [ 256, 1, 1 ] ],
      [ -1, 1, Conv, [ 256, 3, 1 ] ],
      [ -1, 1, Conv, [ 256, 3, 1 ] ],
      [ -1, 1, Conv, [ 256, 3, 1 ] ],
      [ -1, 1, Conv, [ 256, 3, 1 ] ],
      [ [ -1, -3, -5, -6 ], 1, Concat, [ 1 ] ],
      [ -1, 1, Conv, [ 1024, 1, 1 ] ],  # 37

      [ -1, 1, MP, [ ] ],
      [ -1, 1, Conv, [ 512, 1, 1 ] ],
      [ -3, 1, Conv, [ 512, 1, 1 ] ],
      [ -1, 1, Conv, [ 512, 3, 2 ] ],
      [ [ -1, -3 ], 1, Concat, [ 1 ] ],  # 42-P5/32
      [ -1, 1, Conv, [ 256, 1, 1 ] ],
      [ -2, 1, Conv, [ 256, 1, 1 ] ],
      [ -1, 1, Conv, [ 256, 3, 1 ] ],
      [ -1, 1, Conv, [ 256, 3, 1 ] ],
      [ -1, 1, Conv, [ 256, 3, 1 ] ],
      [ -1, 1, Conv, [ 256, 3, 1 ] ],
      [ [ -1, -3, -5, -6 ], 1, Concat, [ 1 ] ],
      [ -1, 1, Conv, [ 1024, 1, 1 ] ],  # 50
    ]

  # yolov7 head
  head:
    [ [ -1, 1, SPPCSPC, [ 512 ] ], # 51

      [ -1, 1, Conv, [ 256, 1, 1 ] ],
      [ -1, 1, nn.Upsample, [ None, 2, 'nearest' ] ],
      [ 37, 1, Conv, [ 256, 1, 1 ] ], # route backbone P4
      [ [ -1, -2 ], 1, Concat, [ 1 ] ],

      [ -1, 1, Conv, [ 256, 1, 1 ] ],
      [ -2, 1, Conv, [ 256, 1, 1 ] ],
      [ -1, 1, Conv, [ 128, 3, 1 ] ],
      [ -1, 1, Conv, [ 128, 3, 1 ] ],
      [ -1, 1, Conv, [ 128, 3, 1 ] ],
      [ -1, 1, Conv, [ 128, 3, 1 ] ],
      [ [ -1, -2, -3, -4, -5, -6 ], 1, Concat, [ 1 ] ],
      [ -1, 1, Conv, [ 256, 1, 1 ] ], # 63

      [ -1, 1, Conv, [ 128, 1, 1 ] ],
      [ -1, 1, nn.Upsample, [ None, 2, 'nearest' ] ],
      [ 24, 1, Conv, [ 128, 1, 1 ] ], # route backbone P3
      [ [ -1, -2 ], 1, Concat, [ 1 ] ],

      [ -1, 1, Conv, [ 128, 1, 1 ] ],
      [ -2, 1, Conv, [ 128, 1, 1 ] ],
      [ -1, 1, Conv, [ 64, 3, 1 ] ],
      [ -1, 1, Conv, [ 64, 3, 1 ] ],
      [ -1, 1, Conv, [ 64, 3, 1 ] ],
      [ -1, 1, Conv, [ 64, 3, 1 ] ],
      [ [ -1, -2, -3, -4, -5, -6 ], 1, Concat, [ 1 ] ],
      [ -1, 1, Conv, [ 128, 1, 1 ] ], # 75

      [ -1, 1, MP, [ ] ],
      [ -1, 1, Conv, [ 128, 1, 1 ] ],
      [ -3, 1, Conv, [ 128, 1, 1 ] ],
      [ -1, 1, Conv, [ 128, 3, 2 ] ],
      [ [ -1, -3, 63 ], 1, Concat, [ 1 ] ],

      [ -1, 1, Conv, [ 256, 1, 1 ] ],
      [ -2, 1, Conv, [ 256, 1, 1 ] ],
      [ -1, 1, Conv, [ 128, 3, 1 ] ],
      [ -1, 1, Conv, [ 128, 3, 1 ] ],
      [ -1, 1, Conv, [ 128, 3, 1 ] ],
      [ -1, 1, Conv, [ 128, 3, 1 ] ],
      [ [ -1, -2, -3, -4, -5, -6 ], 1, Concat, [ 1 ] ],
      [ -1, 1, Conv, [ 256, 1, 1 ] ], # 88

      [ -1, 1, MP, [ ] ],
      [ -1, 1, Conv, [ 256, 1, 1 ] ],
      [ -3, 1, Conv, [ 256, 1, 1 ] ],
      [ -1, 1, Conv, [ 256, 3, 2 ] ],
      [ [ -1, -3, 51 ], 1, Concat, [ 1 ] ],

      [ -1, 1, Conv, [ 512, 1, 1 ] ],
      [ -2, 1, Conv, [ 512, 1, 1 ] ],
      [ -1, 1, Conv, [ 256, 3, 1 ] ],
      [ -1, 1, Conv, [ 256, 3, 1 ] ],
      [ -1, 1, Conv, [ 256, 3, 1 ] ],
      [ -1, 1, Conv, [ 256, 3, 1 ] ],
      [ [ -1, -2, -3, -4, -5, -6 ], 1, Concat, [ 1 ] ],
      [ -1, 1, Conv, [ 512, 1, 1 ] ], # 101

      [ 75, 1, Conv, [ 256, 3, 1 ] ],
      [ 88, 1, Conv, [ 512, 3, 1 ] ],
      [ 101, 1, Conv, [ 1024, 3, 1 ] ],

      [ [ 102, 103, 104 ], 1, ISegment, [ nc, anchors, 32, 256 ] ],  # Detect(P3, P4, P5)
    ]


# ===========Evaluation setting===========
evaluation:
  weight: './weight.pth'
  nms_thres: 0.5
  conf_thres: 0.001
  imgsz: 640
  source: './data/coco'



