model_name: 'EfficientAD'
model_dir_name: 'anomalib'

dataset:
  path: "./datasets/white_original_class_4"
  normal_dir: ""
  abnormal_dir: ""
  mask_dir: ""
  normal_test_dir: ""
cfg_file: "./model_zoo/anomalib/src/anomalib/models/efficient_ad/config.yaml"
