# ===========Dataset===========
coco_root: "D:/Heng_shared/AOI-Project/data/1500/coco/original_class_2"
pretrained_weight: " "


# ===========Augmentation===========
hsv_h: 0.15  # image HSV-Hue augmentation (fraction)
hsv_s: 0.7  # image HSV-Saturation augmentation (fraction)
hsv_v: 0.4  # image HSV-Value augmentation (fraction)
degrees: 0.  # image rotation (+/- deg)
translate: 0.2  # image translation (+/- fraction)
scale: 0.9  # image scale (+/- gain)
shear: 0.  # image shear (+/- deg)
perspective: 0.  # image perspective (+/- fraction), range 0-0.001
flipud: 0.  # image flip up-down (probability)
fliplr: 0.5  # image flip left-right (probability)

# ===========Training===========
model_type: "facebook/sam-vit-base"
batch_size: 4
eval_interval: 25
save_interval: 25
shuffle: True
use_points: False
use_boxes: True
device: 0
end_epoch: 200
num_workers: 0

# ===========Optimizer===========
optimizer: "Adam" # SGD縲、dam縲、damW
weight_decay: 0.0
lr: 0.001
minimum_lr: 0.0
momentum: 0.937 # For SGD
betas_0: 0.936 # For Adam縲、damW
betas_1: 0.999 # For Adam縲、damW





