# ===========Dataset===========
coco_root: "D:/Heng_shared/AOI-Project/data/1500/coco/original_class_2"
output_path: "D:/Heng_shared/AOI-Project/model_zoo/sa/weight/weight.pt"
pretrained_weight: " "

# ===========Training===========
model_type: "facebook/sam-vit-base"
start_epoch: 0
end_epoch: 200
batch_size: 4
eval_interval: 10
save_interval: 10
shuffle: True
use_points: False
use_boxes: False
device: 0

# Optimizer
optimizer: "Adam" # SGD縲、dam縲、damW
weight_decay: 0.0
start_factor: 0.2
momentum: 0.937 # For SGD
betas_0: 0.936 # For Adam縲、damW
betas_1: 0.999 # For Adam縲、damW
lr: 0.00001 # For All
minimum_lr: 0.0 # Minimum learning rate
warmup_epoch: 3




