# ===========Dataset===========
coco_root: "D:/Heng_shared/AOI-Project/data/1500/coco/original_class_2"

# ===========Augmentation===========
hsv_h: 0.15  # image HSV-Hue augmentation (fraction)
hsv_s: 0.7  # image HSV-Saturation augmentation (fraction)
hsv_v: 0.8  # image HSV-Value augmentation (fraction)
degrees: 20  # image rotation (+/- deg)
translate: 0.05  # image translation (+/- fraction)
scale: 1.0  # image scale (+/- gain)
shear: 5  # image shear (+/- deg)
perspective: 0.0  # image perspective (+/- fraction)
flipud: 0.5  # image flip up-down (probability)
fliplr: 0.5  # image flip left-right (probability)


# ===========Training===========
model_type: "facebook/sam-vit-base"
batch_size: 4
eval_interval: 1
save_interval: 25
shuffle: True
use_points: False
use_boxes: True
device: 0
end_epoch: 200
num_workers: 2
weight: " "

# ===========Optimizer===========
optimizer: "Adam" # SGD縲、dam縲、damW
weight_decay: 0.0
lr: 0.001
minimum_lr: 0.0
momentum: 0.937 # For SGD
betas_0: 0.936 # For Adam縲、damW
betas_1: 0.999 # For Adam縲、damW





