_base_: [ "./base/model/CO-DETR/r50.yaml", # model
          "./base/evaluation/object_detection.yaml", # task
          "./base/dataset.yaml", # dataset
          "./base/hyp.yaml" # hyperparameter
]


# ===========Dataset===========
number_of_class: 2
coco_root: /home/miislab-server2/MiiSLab_NAS/Student_Work/Heng/Backup/DESKTOP-AP518TL/D/AOI/solovision_vs_yolov8/1500_Dataset_coco
class_names:
  - "Pass"
  - "Defect"

# ===========Hyperparameter===========
optimizer: "AdamW" # Adam、AdamW、SGD
weight: " "
start_epoch: 0
end_epoch: 500
warmup_epoch: 3
initial_lr: 0.00005 # Initial learning rate
lr: 0.0002 # The learning rate after warmup
minimum_lr: 0.0 # Minimum learning rate
batch_size: 2
imgsz: [1024, 1024]
use_patch: false
device: "0"

