_base_: [ "./base/model/EfficientDet/d0.yaml", # model
          "./base/evaluation/object_detection.yaml", # task
          "./base/dataset.yaml", # dataset
          "./base/hyp.yaml" # hyperparameter
]


# ===========Dataset===========
number_of_class: 2
coco_root: "./data/1500/coco/original_class_2"
class_names:
  - "Pass"
  - "Defect"
class_color: # B G R
  - [0, 255, 0]
  - [0, 0, 255]

# ===========Hyperparameter===========
optimizer: "AdamW" # Adam、AdamW、SGD
weight: " "
start_epoch: 0
end_epoch: 900
warmup_epoch: 3
initial_lr: 0.00005 # Initial learning rate
lr: 0.0002 # The learning rate after warmup
minimum_lr: 0.0 # Minimum learning rate
batch_size: 3
imgsz: [1536, 1536] # must can be divided by 512
save_period: 10
use_patch: false
device: "0"

