_base_: [ "./base/model/EfficientAD/efficient_ad_base.yaml", # model
          "./base/evaluation/object_detection.yaml", # task
          "./base/dataset.yaml", # dataset
          "./base/hyp.yaml" # hyperparameter
]

# ===========Dataset===========
coco_root: "./data/white_controller/coco/original_class_4"
dataset_dir: './data/bottle'
number_of_class: 4
class_names:
  - "broken_large"
  - "broken_small"
  - "contamination"

# ===========Hyperparameter===========
#optimizer: "AdamW" # Adam、AdamW、SGD
#weight: " "
start_epoch: 0
end_epoch: 10
#warmup_epoch: 3
#initial_lr: 0.0003 # Initial learning rate
lr: 0.001 # The learning rate after warmup
#minimum_lr: 0.0001 # Minimum learning rate
batch_size: 4
imgsz: [512, 512]
#use_patch: false
device: 0

