_base_: [ "./base/model/Mask2Former/r50.yaml", # model
          "./base/evaluation/instance_segmentation.yaml", # task
          "./base/dataset.yaml", # dataset
          "./base/hyp.yaml" # hyperparameter
]


# ===========Dataset===========
number_of_class: 2
coco_root: "./data/1500/coco/original_class_2"
class_names:
  - "Pass"
  - "Defect"
class_color: # B G R
  - [0, 255, 0]
  - [0, 0, 255]

# ===========Augmentation===========
hsv_h: 0.15  # image HSV-Hue augmentation (fraction)
hsv_s: 0.7  # image HSV-Saturation augmentation (fraction)
hsv_v: 0.4  # image HSV-Value augmentation (fraction)
degrees: 10  # image rotation (+/- deg)
translate: 0.1  # image translation (+/- fraction)
scale: 0.9  # image scale (+/- gain)
shear: 0.  # image shear (+/- deg)
perspective: 0.  # image perspective (+/- fraction), range 0-0.001
flipud: 0.  # image flip up-down (probability)
fliplr: 0.5  # image flip left-right (probability)

# ===========Hyperparameter===========
optimizer: "AdamW" # Adam、AdamW、SGD
weight: " "
end_epoch: 100
warmup_epoch: 3
save_period: 25
eval_period: 25
initial_lr: 0.000005 # Initial learning rate
lr: 0.0002 # The learning rate after warmup
minimum_lr: 0.0 # Minimum learning rate
batch_size: 2
imgsz: [1600, 1600]
device: "0"

