_base_: [ "./base/model/Mask2Former/r101.yaml", # model
          "./base/evaluation/instance_segmentation.yaml", # task
          "./base/dataset.yaml", # dataset
          "./base/hyp.yaml" # hyperparameter
]


# ===========Dataset===========
coco_root: null

# ===========Augmentation===========
hsv_h: 0.15  # image HSV-Hue augmentation (fraction), range 0-1
hsv_s: 0.7  # image HSV-Saturation augmentation (fraction), range 0-1
hsv_v: 0.4  # image HSV-Value augmentation (fraction), range 0-1
degrees: 10  # image rotation (+/- deg), range 0-360
translate: 0.1  # image translation (+/- fraction), range 0-1
scale: 0.9  # image scale (+/- gain), range 0-1, 1 means no scaling
shear: 0.  # image shear (+/- deg), range 0-180
perspective: 0.5  # image perspective (+/- fraction), range 0-1
flipud: 0.  # image flip up-down (probability), range 0-1
fliplr: 0.5  # image flip left-right (probability), range 0-1

# ===========Hyperparameter===========
optimizer: "AdamW" # Adam、AdamW、SGD
weight: null
end_epoch: 50
warmup_epoch: 3
initial_lr: 0.000005 # Initial learning rate
lr: 0.0002 # The learning rate after warmup
minimum_lr: 0.0000005 # Minimum learning rate
batch_size: 1
imgsz: [1600, 1600]
num_queries: 10
save_period: 5
eval_period: 5
device: "0"

