_base_: [ "./base/model/YOLO-v7/yolov7_obj_base.yaml", # model
          "./base/evaluation/object_detection.yaml", # task
          "./base/dataset.yaml", # dataset
          "./base/hyp.yaml" # hyperparameter
]

# ===========Model===========
train_txt: " "
val_txt: " "

# ===========Dataset===========
number_of_class: 16
coco_root: "./data/coco/original_class_16"
class_names:
  - "Border"
  - "black_Marks"
  - "Bright_Marks"
  - "Pass"
  - "Dirty"
  - "Friction"
  - "Black_point"
  - "Buttom_scratches"
  - "Small_scratches"
  - "AnotherColor"
  - "Severe_scratches"
  - "Glossy"
  - "ReturnPoint"
  - "Assembly"
  - "Scractches_Blackbackground"
  - "Buttom_Friction"


# ===========Hyperparameter===========
optimizer: "SGD" # Adam、AdamW、SGD
weight: " "
start_epoch: 0
end_epoch: 50
warmup_epoch: 3
initial_lr: 0.003 # Initial learning rate
lr: 0.01 # The learning rate after warmup
minimum_lr: 0.001 # Minimum learning rate
batch_size: 8
imgsz: [1024, 1024]
use_patch: false
device: "0"



