_base_: [ "./base/model/YOLO-v7/yolov7_obj_base.yaml", # model
          "./base/evaluation/object_detection.yaml", # task
          "./base/dataset.yaml", # dataset
          "./base/hyp.yaml" # hyperparameter
]

# ===========Model===========
train_txt: "./data/yoloBbox/orininal_class_16/train_list.txt"
val_txt: "./data/yoloBbox/orininal_class_16/val_list.txt"

# ===========Dataset===========
number_of_class: 16
coco_root: "./data/coco/original_class_16"
class_names:
  - "Border"
  - "black_Marks"
  - "Bright_Marks"
  - "Pass"
  - "Dirty"
  - "Friction"
  - "Black_point"
  - "Buttom_scratches"
  - "Small_scratches"
  - "AnotherColor"
  - "Severe_scratches"
  - "Glossy"
  - "ReturnPoint"
  - "Assembly"
  - "Scractches_Blackbackground"
  - "Buttom_Friction"


# ===========Hyperparameter===========
optimizer: "Adam" # Adam、AdamW、SGD
weight: " "
start_epoch: 0
end_epoch: 50
lr: 0.01
start_factor: 0.3
batch_size: 4
imgsz: [1024, 1024]
use_patch: false
device: "0"



