_base_: [ "./base/model/YOLO-v7/yolov7_obj_base.yaml", # model
          "./base/evaluation/object_detection.yaml", # task
          "./base/dataset.yaml", # dataset
          "./base/hyp.yaml" # hyperparameter
]


# ===========Dataset===========
coco_root: "./data/black_controller/coco/original_class_1"
train_txt: "./data/black_controller/yoloBbox/original_class_1/train_list.txt"
val_txt: "./data/black_controller/yoloBbox/original_class_1/val_list.txt"
number_of_class: 1
class_names:
  - "Defect"

# ===========Hyperparameter===========
optimizer: "AdamW" # Adam、AdamW、SGD
weight: " "
start_epoch: 0
end_epoch: 50
warmup_epoch: 3
initial_lr: 0.003 # Initial learning rate
lr: 0.01 # The learning rate after warmup
minimum_lr: 0.001 # Minimum learning rate
batch_size: 8
imgsz: [1024, 1024]
use_patch: false
device: "0"



