_base_: [ "./base/model/YOLO-v7/yolov7_obj_base_d6.yaml", # model
          "./base/evaluation/object_detection.yaml", # task
          "./base/dataset.yaml", # dataset
          "./base/augmentation.yaml", # Augmentation
          "./base/hyp.yaml" # hyperparameter
]


# ===========Dataset===========
coco_root: "./data/1500/coco/original_class_2"
train_txt: /home/miislab-server2/MiiSLab_NAS/Student_Work/Heng/AOI-New-Dataset/1500/yoloBbox/patch_1024_class_2/train_list.txt
val_txt: /home/miislab-server2/MiiSLab_NAS/Student_Work/Heng/AOI-New-Dataset/1500/yoloBbox/patch_1024_class_2/val_list.txt
number_of_class: 2
class_names:
  - "Pass"
  - "Defect"
class_color: # B G R
  - [0, 255, 0]
  - [0, 0, 255]

# ===========Augmentation===========
hsv_h: 0.15  # image HSV-Hue augmentation (fraction)
hsv_s: 0.7  # image HSV-Saturation augmentation (fraction)
hsv_v: 0.4  # image HSV-Value augmentation (fraction)
degrees: 0.  # image rotation (+/- deg)
translate: 0.2  # image translation (+/- fraction)
scale: 0.9  # image scale (+/- gain)
shear: 0.  # image shear (+/- deg)
perspective: 0.  # image perspective (+/- fraction), range 0-0.001
flipud: 0.  # image flip up-down (probability)
fliplr: 0.5  # image flip left-right (probability)
mosaic: 1.  # image mosaic (probability)
mixup: 0.15  # image mixup (probability)
copy_paste: 0.0  # segment copy-paste (probability)

# ===========Hyperparameter===========
optimizer: "SGD" # Adam、AdamW、SGD
weight: " "
end_epoch: 1200
warmup_epoch: 3
initial_lr: 0.003 # Initial learning rate
lr: 0.01 # The learning rate after warmup
minimum_lr: 0.001 # Minimum learning rate
batch_size: 6
save_period: 25
eval_period: 25
imgsz: [ 1024, 1024 ] # [train, test] image size
use_patch: True
patch_size: 1024
step: 512
device: "0"
