_base_: [ "./base/model/yolov7_obj_base.yaml", # model
          "./base/evaluation/object_detection.yaml", # task
          "./base/dataset.yaml", # dataset
          "./base/hyp.yaml" # hyperparameter
]

# ===========Model===========
train_txt: /home/miislab-server/Heng/Heng_shared/AOI-Project/data/yoloBox/train_list.txt
val_txt: /home/miislab-server/Heng/Heng_shared/AOI-Project/data/yoloBox/val_list.txt

# ===========Dataset===========
number_of_class: 16
coco_root: "../coco"
class_names:
  - "Border"
  - "black_Marks"
  - "Bright_Marks"
  - "Pass"
  - "Dirty"
  - "Friction"
  - "Black_point"
  - "Buttom_scratches"
  - "Small_scratches"
  - "AnotherColor"
  - "Severe_scratches"
  - "Glossy"
  - "ReturnPoint"
  - "Assembly"
  - "Scractches_Blackbackground"
  - "Buttom_Friction"


# ===========Hyperparameter===========
optimizer: "AdamW" # Adam、AdamW、SGD
weight: ./work_dirs/Yolov7Obj_13/weights/best.pt
start_epoch: 0
end_epoch: 500
lr: 0.01
start_factor: 0.3
batch_size: 8
imgsz: [1024, 1024]
use_patch: false
device: "1"



