_base_: [ "./base/model/YOLO-v7/yolov7_inSeg_base.yaml", # model
          "./base/evaluation/instance_segmentation.yaml", # task
          "./base/dataset.yaml", # dataset
          "./base/hyp.yaml" # hyperparameter
]

# ===========Dataset===========
coco_root: /home/miislab-server2/MiiSLab_NAS/Student_Work/Heng/Backup/DESKTOP-AP518TL/D/AOI/solovision_vs_yolov8/1500_Dataset_coco
train_dir: /home/miislab-server2/MiiSLab_NAS/Student_Work/Heng/Backup/DESKTOP-AP518TL/D/AOI/solovision_vs_yolov8/1500_Dataset_inSeg/train
val_dir: /home/miislab-server2/MiiSLab_NAS/Student_Work/Heng/Backup/DESKTOP-AP518TL/D/AOI/solovision_vs_yolov8/1500_Dataset_inSeg/test
number_of_class: 2
class_names:
  - "Pass"
  - "Defect"

# ===========Hyperparameter===========
optimizer: "SGD" # Adam、AdamW、SGD
weight:  /home/miislab-server2/Heng/Heng_shared/AOI-Project/work_dirs/train/yolov7inSeg_best/best.pt
start_epoch: 0
end_epoch: 500
warmup_epoch: 3
initial_lr: 0.003 # Initial learning rate
lr: 0.01 # The learning rate after warmup
minimum_lr: 0.001 # Minimum learning rate
batch_size: 8
imgsz: [1024, 1024]
use_patch: true
device: "0"

