_base_: ['./base/yolov7_seg_base.yaml',
         './base/default_setting.yaml']

# ===========Default setting===========
work_dir: './work_dirs/Yolov7Seg'
coco_root: "D:/Heng_shared/AOI-Project/tools/coco"
nms_thres: 0.5
conf_thres: 0.001

# ===========Hyperparameter and file===========
optimizer: 'Adam'
weight: "//DESKTOP-PPOB8AK/share/AOI_result/Instance Segmentation/yolov7/1024_Adam_202312061402/weights/best.pt"
epochs: 50
batch_size: 8
imgsz: [1024, 1024]


# ===========Data file===========
data_file:
  train: /home/miislab-server/Heng/Heng_shared/yoloSeg/train
  val: /home/miislab-server/Heng/Heng_shared/yoloSeg/test

  # number of classes
  nc: 16

  # class names
  names: ["Border", "black_Marks", "Bright_Marks", "Pass", "Dirty", "Friction", "Black_point", "Buttom_scratches", "Small_scratches", "AnotherColor", "Severe_scratches", "Glossy", "ReturnPoint", "Assembly", "Scractches_Blackbackground", "Buttom_Friction" ]
