_base_: [ "./base/model/YOLO-v7/yolov7_inSeg_base.yaml", # model
          "./base/evaluation/instance_segmentation.yaml", # task
          "./base/dataset.yaml", # dataset
          "./base/hyp.yaml" # hyperparameter
]

# ===========Model===========
train_dir: "./data/yoloSeg/original_class_4/train"
val_dir: "./data/yoloSeg/original_class_4/test"

# ===========Dataset===========
number_of_class: 4
coco_root: "./data/coco/original_class_4"
class_names:
  - "Scratch"
  - "Friction"
  - "Dirty"
  - "Assembly"

# ===========Hyperparameter===========
optimizer: "AdamW" # Adam、AdamW、SGD
weight: "D:/Heng_shared/AOI-Project/work_dirs/train/Yolov7inSeg_2/weights/best.pt"
start_epoch: 0
end_epoch: 50
warmup_epoch: 3
initial_lr: 0.003 # Initial learning rate
lr: 0.01 # The learning rate after warmup
minimum_lr: 0.001 # Minimum learning rate
batch_size: 8
imgsz: [1024, 1024]
use_patch: false
device: "0"

