_base_: [ "./base/model/YOLO-v7/yolov7_inSeg_base.yaml", # model
          "./base/evaluation/instance_segmentation.yaml", # task
          "./base/dataset.yaml", # dataset
          "./base/hyp.yaml" # hyperparameter
]

# ===========Model===========
train_dir: " "
val_dir: " "

# ===========Dataset===========
number_of_class: 4
coco_root: "./data/coco/original_class_16"
class_names:
  - "Scratch"
  - "Friction"
  - "Dirty"
  - "Assembly"

# ===========Hyperparameter===========
optimizer: "SGD" # Adam、AdamW、SGD
weight: "Z:/Student_Work/Heng/AOI_result/Instance Segmentation/yolov7/1024_Adam_202312061402/weights/best.pt"
start_epoch: 0
end_epoch: 50
warmup_epoch: 3
initial_lr: 0.003 # Initial learning rate
lr: 0.01 # The learning rate after warmup
minimum_lr: 0.001 # Minimum learning rate
batch_size: 8
imgsz: [1024, 1024]
use_patch: false
device: "0"

