_base_: [ "./base/model/YOLO-v7/yolov7_inSeg_base.yaml", # model
          "./base/evaluation/instance_segmentation.yaml", # task
          "./base/dataset.yaml", # dataset
          "./base/hyp.yaml" # hyperparameter
]

# ===========Model===========
train_txt: "./data/yoloSeg/train"
val_txt: "./data/yoloSeg/test"

# ===========Dataset===========
number_of_class: 16
coco_root: " "
class_names:
  - "Border"
  - "black_Marks"
  - "Bright_Marks"
  - "Pass"
  - "Dirty"
  - "Friction"
  - "Black_point"
  - "Buttom_scratches"
  - "Small_scratches"
  - "AnotherColor"
  - "Severe_scratches"
  - "Glossy"
  - "ReturnPoint"
  - "Assembly"
  - "Scractches_Blackbackground"
  - "Buttom_Friction"


# ===========Hyperparameter===========
optimizer: "SGD" # Adam、AdamW、SGD
weight: " "
start_epoch: 0
end_epoch: 50
lr: 0.01
start_factor: 0.3
batch_size: 8
imgsz: [1024, 1024]
use_patch: false
device: "0"

