_base_: [
  "./base/evaluation/common_metrics.yaml"
]

nms_thres: 0.5
conf_thres: 0.001
task: "instance_segmentation"

sheet_names:
  - "All"
  - "Each class(box, mAP)"
  - "Each class(box, mAR)"
  - "Each class(mask, mAP)"
  - "Each class(mask, mAR)"

metrics_for_all:
  - "mAP_0.5(Box)"
  - "mAP_0.5:0.95(Box)"
  - "mAR_0.5:0.95(Box)"
  - "mAP_0.5(Mask)"
  - "mAP_0.5:0.95(Mask)"
  - "mAR_0.5:0.95(Mask)"

metrics_for_each:
  - "mAP_0.5(Box)"
  - "mAR_0.5:0.95(Box)"
  - "mAP_0.5(Mask)"
  - "mAR_0.5:0.95(Mask)"