_base_: [
  "./base/evaluation/common_metrics.yaml"
]

nms_thres: 0.5
conf_thres: 0.2
task: "object_detection"
sheet_names:
  - "All"
  - "Each class(Precision, Box)"
  - "Each class(Recall, Box)"

metrics_for_all:
  - "Precision(Box)"
  - "Recall(Box)"
  - "mAP_0.5(Box)"
  - "mAP_0.75(Box)"
  - "mAP_0.5:0.95(Box)"

metrics_for_each:
  - "Precision(Box)"
  - "Recall(Box)"