_base_: [
  "./base/evaluation/common_metrics.yaml"
]

nms_thres: 0.5
conf_thres: 0.001
task: "object_detection"
sheet_names:
  - "All"
  - "Each class(box, mAP)"
  - "Each class(box, mAR)"

metrics:
  - "Inference Time(ms)"
  - "NMS Time(ms)"
  - "mAP_0.5(Box)"
  - "mAP_0.5:0.95(Box)"
  - "mAR_0.5:0.95(Box)"
