_base_: [
  "./base/evaluation/common_metrics.yaml"
]

nms_thres: 0.5
conf_thres: 0.001
task: "object_detection"
sheet_names:
  - "All"
  - "Each class(box, mAP)"
  - "Each class(box, mAR)"

metrics_for_all:
  - "mAP_0.5(Box)"
  - "mAP_0.5:0.95(Box)"
  - "mAR_0.5:0.95(Box)"

metrics_for_each:
  - "mAP_0.5(Box)"
  - "mAR_0.5:0.95(Box)"