_base_: [ "./base/model/YOLO-v7/yolov7_obj_base.yaml", # model
          "./base/evaluation/object_detection.yaml", # task
          "./base/dataset.yaml", # dataset
          "./base/hyp.yaml" # hyperparameter
]


# ===========Model===========
train_txt: "./data/yoloBbox/patch_1024_class_4/train_list.txt"
val_txt: "./data/yoloBbox/patch_1024_class_4/test_list.txt"

# ===========Dataset===========
number_of_class: 4
coco_root: "./data/coco/patch_1024_class_4"
class_names:
  - "Scratch"
  - "Friction"
  - "Dirty"
  - "Assembly"

# ===========Hyperparameter===========
optimizer: "AdamW" # Adam、AdamW、SGD
imgsz: [1024, 1024]
use_patch: true

weight: " "
start_epoch: 0
end_epoch: 50
warmup_epoch: 3
initial_lr: 0.003 # Initial learning rate
lr: 0.01 # The learning rate after warmup
minimum_lr: 0.001 # Minimum learning rate
batch_size: 8
device: "0"


